server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:ec2-3-219-135-162.compute-1.amazonaws.com:5432/dbs6j51vvjhcrh
    username: ewfjwhzpbucebp
    password: 329bee837bc385c4b0a121f939f205ecf92f99d5a6f3d46eeb789d7df0326388
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
file:
  path: '/project/uploads/'




